name: metta-run CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Metta setup script
      run: |
        curl -fsSL https://raw.githubusercontent.com/iCog-Labs-Dev/metta-prebuilt-binary/main/install.sh | bash

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Navigate to the metta-run directory
      working-directory: ./metta-run
      run: |
        echo "Moved to metta-run directory"

    - name: Run tests
      working-directory: ./metta-run
      run: cargo test --verbose

    - name: Ensure metta-run is executable
      run: chmod +x $HOME/metta-bin/metta-run
